#!/usr/bin/env python3
"""Renders the legal pages' Markdown sources through the kit, the way the MarsDawn app's own
preview renders a document, and vendors the kit assets that HTML needs.

content/legal/<slug>.<locale>.md is the single source of truth for each legal page's text
(privacy and support; there is no terms page in this site yet). This script:

- builds tools/hero-render (pinned to the kit tag the site already uses elsewhere) and runs
  each source through MarsDawnKit's MarkdownRenderer, the same renderer the app's preview uses;
- strips the per-render `data-line` attributes and heading `id`s that the renderer adds for the
  app's editor sync, which the site doesn't need (build_pages.py assigns its own heading ids,
  from the English text, so an anchor works in every locale — see add_toc);
- writes the result to content/legal/<slug>.<locale>.rendered.html, which build_pages.py reads
  at every ordinary build (no Swift needed there, so CI on Ubuntu keeps working);
- vendors public/assets/preview.css and public/assets/themes.css from the exact pinned kit tag,
  the two stylesheets MarkdownRenderer's own HTML needs to look like the app's preview;
- records every input's sha256 in content/legal/manifest.json, so
  scripts/check_legal_render.py can catch a source edited without a re-render, or a generated
  file edited by hand, without needing Swift or macOS itself (it runs in CI).

This script needs macOS (the kit is a Swift package); the check does not. Rerun it after
editing a content/legal/*.md source, after the kit tag pinned in tools/hero-render/Package.swift
changes, or if tools/hero-render/Sources itself changes.

    python3 scripts/render_legal.py
"""
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content" / "legal"
RENDERER = ROOT / "tools" / "hero-render"
ASSETS = ROOT / "public" / "assets"
MANIFEST = CONTENT / "manifest.json"

# Every legal page this site has a Markdown source for. (terms.md doesn't exist yet: issue #33's
# plan mentions it, but there is no terms page on the site today, so there is nothing to convert.)
LOCALES = ["en", "zh-hant", "zh-hans", "ja"]
SLUGS = ["privacy", "support"]

GENERATED_NOTE = (
    "<!-- Generated by scripts/render_legal.py from {source}. Do not edit by hand: "
    "edit the .md source and rerun the script. -->\n"
)


def sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def kit_tag() -> str:
    text = (RENDERER / "Package.swift").read_text(encoding="utf-8")
    m = re.search(r'exact:\s*"([^"]+)"', text)
    assert m, "tools/hero-render/Package.swift: couldn't find the kit's pinned exact version"
    return m[1]


def build_renderer() -> Path:
    subprocess.run(["swift", "build", "-c", "release", "--package-path", str(RENDERER)],
                    check=True, capture_output=True)
    return RENDERER / ".build" / "release" / "hero-render"


def render_markdown(binary: Path, markdown: str) -> str:
    return subprocess.run([str(binary)], input=markdown, check=True, capture_output=True, text=True).stdout


def theme_css(binary: Path) -> str:
    return subprocess.run([str(binary), "--theme-css"], check=True, capture_output=True, text=True).stdout


# The kit's parser turns on CMARK_OPT_SMART (MarkdownParsing.swift), which the app's own
# preview also renders with: a straight ' or " becomes a curly quote. That's the right
# behaviour for a document someone writes today, but these sources are a mechanical,
# byte-for-byte transcription of legal text that was already reviewed and published with
# straight ASCII quotes in en/zh-Hant/ja, and this slice's hard constraint is that the words
# don't move, not even a glyph. zh-Hans is different: its own copy already writes curly
# "…" on purpose (not the zh-Hant/ja convention of 「…」), so there's nothing of its to
# revert, and reverting on sight would instead turn its intentional curly quotes into ASCII
# ones — a real text change in the other direction. So the substitution is reverted only for
# the specific mark(s) a given locale's *source* actually spells straight; a locale whose
# source has none (zh-Hans) is left untouched. (No locale's prose has a bare `--` or `...`
# for SMART to touch either way; see the PR description for how that was checked.)
def straighten_quotes(html: str, source: str) -> str:
    mapping = {}
    if "'" in source:
        mapping["‘"] = "'"
        mapping["’"] = "'"
    if '"' in source:
        mapping["“"] = '"'
        mapping["”"] = '"'
    for smart, straight in mapping.items():
        html = html.replace(smart, straight)
    return html


def clean_fragment(html: str, source: str) -> str:
    """Strips what the app's editor sync needs (data-line, and heading ids meant to be stable
    across edits to one document) and turns inline `style="text-align:…"` into a class, since the
    site's CSP allows no inline style. Also reverts CMARK_OPT_SMART's quote substitution where
    the source calls for it (see straighten_quotes). Nothing here changes any letter of the
    rendered text."""
    html = re.sub(r' data-line="[^"]*"', "", html)
    html = re.sub(r'<h([1-6]) id="[^"]*"', r"<h\1", html)
    html = re.sub(r' style="text-align:(left|center|right)"', r' class="align-\1"', html)
    html = straighten_quotes(html, source)
    assert "data-line=" not in html and "style=" not in html, "the renderer's output changed shape"
    return html.strip() + "\n"


def kit_checkout() -> Path:
    checkout = RENDERER / ".build" / "checkouts" / "mars-dawn-kit"
    assert checkout.is_dir(), f"{checkout} missing; did `swift build` fetch the kit?"
    return checkout


def main() -> None:
    tag = kit_tag()
    binary = build_renderer()
    manifest = {"kit_tag": tag, "pages": {}}

    for slug in SLUGS:
        for locale in LOCALES:
            source = CONTENT / f"{slug}.{locale}.md"
            markdown = source.read_text(encoding="utf-8")
            html = clean_fragment(render_markdown(binary, markdown), markdown)
            out = CONTENT / f"{slug}.{locale}.rendered.html"
            out.write_text(GENERATED_NOTE.format(source=source.name) + html, encoding="utf-8")
            manifest["pages"][source.name] = {"source_sha256": sha256(markdown), "rendered": out.name,
                                              "rendered_sha256": sha256(out.read_text(encoding="utf-8"))}
            print(out)

    # The kit's preview.css is written to own a whole isolated page (the app's own preview
    # WebView): bare `body`, `h1`, `p`, `a`… selectors, and one `html { background: … }`. This
    # site's legal pages are not an isolated page — the same <body> also holds the masthead and
    # footer, styled by site.css — so those bare selectors are wrapped in `@scope` to the
    # `.markdown-body` element render_legal_body wraps the rendered page in. `@scope` doesn't
    # touch a single selector's text (nothing here is "not verbatim from the kit" in that
    # sense): a rule like `body { color: var(--fg) }` still matches only within the scope, so it
    # simply matches nothing outside `.markdown-body`, rather than recolouring the whole page.
    preview_css = (kit_checkout() / "Sources/MarsDawnKit/Resources/Preview/preview.css").read_text(encoding="utf-8")
    scoped_preview_css = f"@scope (.markdown-body) {{\n{preview_css}}}\n"
    (ASSETS / "preview.css").write_text(scoped_preview_css, encoding="utf-8")
    manifest["preview_css_sha256"] = sha256(scoped_preview_css)
    print(ASSETS / "preview.css")

    themes = theme_css(binary)
    (ASSETS / "themes.css").write_text(themes, encoding="utf-8")
    manifest["themes_css_sha256"] = sha256(themes)
    print(ASSETS / "themes.css")

    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(MANIFEST)


if __name__ == "__main__":
    main()
