"""PR B copy, one dict per locale. Plain text only: the generator escapes it for HTML and derives the
FAQPage / HowTo JSON-LD from the same strings. en and zh-hant are the reviewed-first drafts; zh-hans, ja,
de, fr, es and ko are machine drafts from en."""

COPY = {}

COPY["en"] = dict(
    desc="MarsDawn is a native Markdown editor for Mac with live split preview, Mermaid, KaTeX, Quick Look and PDF export. Free to try, then USD 4.99 once.",
    defn="MarsDawn is a native macOS Markdown editor with live split preview, Mermaid diagrams, KaTeX math, Quick Look and PDF export, free to try for 14 days and USD 4.99 once to unlock.",
    ql_link="How Quick Look works",
    faq_h="Questions and answers",
    ui="Quick Look for Markdown",
    home_faq=[
        ("What is MarsDawn?", "MarsDawn is a native Markdown editor for the Mac. It shows a live preview next to the source, draws Mermaid diagrams and KaTeX math, previews Markdown files in Finder with Quick Look, and exports PDF."),
        ("Is MarsDawn a subscription?", "No. MarsDawn is a free download with a 14-day trial of every feature. After that, a single in-app purchase of USD 4.99 unlocks it for good. Nothing renews, and there is no account."),
        ("Does MarsDawn work on iPhone or iPad?", "No. MarsDawn is a Mac app and needs macOS 26 or later. There is no iPhone or iPad app."),
        ("Can Claude Code open files in MarsDawn?", "Yes. The free marsdawn command-line tool has an open command that opens a Markdown file in MarsDawn, so Claude Code, or any agent that can run a shell command, can call it. An opt-in Claude Code hook can open each Markdown file Claude writes or edits."),
        ("Does Quick Look still work after the trial ends?", "Yes. Quick Look in Finder keeps showing your Markdown files whether or not the trial is running. After the trial ends and until you unlock, documents open in MarsDawn with their content covered."),
    ],
    pay_faq=[
        ("How much does MarsDawn cost?", "MarsDawn is a free download from the Mac App Store. You can use every feature for 14 days, and after that a one-time in-app purchase of USD 4.99 unlocks it."),
        ("Is there a subscription?", "No. The unlock is a single purchase, so nothing renews and nothing charges you later. Starting the trial costs nothing either."),
        ("What happens when the 14-day trial ends?", "Until you unlock MarsDawn, you can't read, edit, export or print documents in it: they open with their content covered. Your files stay exactly as you saved them."),
        ("Does Quick Look still work after the trial?", "Yes. Quick Look in Finder works with or without the trial. The free marsdawn command-line tool also keeps exporting Markdown to PDF."),
        ("Do I need an account?", "No. MarsDawn never asks you to create an account."),
    ],
    ql_title="Markdown Quick Look for Mac: preview .md files in Finder · MarsDawn",
    ql_desc="MarsDawn's Quick Look renders Markdown in Finder when you press Space, with Mermaid, KaTeX and highlighted code. It keeps working after the trial ends.",
    ql_h1="Preview Markdown in Finder with Quick Look.",
    ql_lead="Select a Markdown file in Finder and press Space. With MarsDawn installed, Quick Look shows the rendered page instead of plain text.",
    ql_shows_h="What the preview shows",
    ql_shows=[
        "The rendered page, drawn by the same renderer as MarsDawn's preview pane.",
        "Mermaid diagrams, KaTeX math and highlighted code blocks.",
        "The preview theme you picked in MarsDawn, in light or dark.",
        "Web images stay blocked, and pictures stored next to the file can appear as placeholders.",
    ],
    ql_how_h="How to use it",
    ql_how_name="How to preview a Markdown file with Quick Look",
    ql_steps=[
        ("Install MarsDawn.", "Download MarsDawn from the Mac App Store. The Quick Look extension is part of the app."),
        ("Select a Markdown file.", "In Finder, click a .md file once."),
        ("Press Space.", "The rendered preview opens. Press Space again to close it."),
        ("If you see plain text, switch the extension on.", "Open System Settings, go to General ▸ Login Items & Extensions, click the Info button next to Quick Look under Extensions, turn on MarsDawn Preview, then click Done."),
    ],
    ql_trial_h="Not locked by the trial",
    ql_trial_p="Quick Look keeps working after the trial ends. It shows the same rendered preview while the trial runs, after it ends and after you unlock. After the trial ends and until you unlock, MarsDawn's own windows open with their content covered; Finder previews are unchanged. The {pay_link} sets all three stages side by side.",
    ql_pay_link_text="trial and unlock page",
    ql_next_h="Next",
    ql_faq=[
        ("How do I preview a Markdown file in Finder?", "Select the file and press Space. With MarsDawn installed, Quick Look shows the rendered page, with Mermaid diagrams, KaTeX math and highlighted code."),
        ("Does Quick Look still work after the 14-day trial?", "Yes. Quick Look is not locked by the trial. It keeps rendering Markdown files while the trial runs, after it ends and once you unlock."),
        ("Why does Quick Look show plain text?", "The Quick Look extension may be switched off. Open System Settings, go to General ▸ Login Items & Extensions, click the Info button next to Quick Look under Extensions, turn on MarsDawn Preview, then click Done."),
        ("Does Quick Look cost extra?", "No. The Quick Look extension is part of MarsDawn, with no separate purchase. MarsDawn is a free download with a 14-day trial and a one-time USD 4.99 unlock, and Quick Look works with or without the trial."),
        ("Which version of macOS does it need?", "MarsDawn needs macOS 26 or later."),
    ],
)

COPY["zh-hant"] = dict(
    desc="MarsDawn 是 Mac 原生 Markdown 編輯器：即時分割預覽、Mermaid、KaTeX、快速查看、PDF 輸出。免費試用，之後一次 USD 4.99 解鎖。",
    defn="MarsDawn 是 macOS 原生的 Markdown 編輯器，有即時分割預覽、Mermaid 圖表、KaTeX 數學式、快速查看與 PDF 輸出，可免費試用 14 天，之後只要一次 USD 4.99 解鎖。",
    ql_link="快速查看怎麼用",
    faq_h="常見問題",
    ui="Markdown 快速查看",
    home_faq=[
        ("MarsDawn 是什麼？", "MarsDawn 是 Mac 上原生的 Markdown 編輯器。原始碼旁邊有即時預覽，能畫出 Mermaid 圖表和 KaTeX 數學式，在 Finder 用快速查看預覽 Markdown 檔案，也能輸出 PDF。"),
        ("MarsDawn 要訂閱嗎？", "不用。MarsDawn 免費下載，14 天內所有功能都能試用；之後一次 USD 4.99 的 App 內購買就能永久解鎖。沒有任何續訂，也不需要帳號。"),
        ("MarsDawn 有 iPhone 或 iPad 版嗎？", "沒有。MarsDawn 是 Mac app，需要 macOS 26 或更新版本，沒有 iPhone 或 iPad 版。"),
        ("Claude Code 可以用 MarsDawn 開檔案嗎？", "可以。免費的 marsdawn 命令列工具有 open 指令，能用 MarsDawn 開啟 Markdown 檔案，所以 Claude Code，或任何能執行 shell 指令的 agent，都能呼叫它。另有一個需要自行啟用的 Claude Code hook，可以在 Claude 寫入或編輯 Markdown 檔案時自動開啟。"),
        ("試用結束後，快速查看還能用嗎？", "能。不論試用是否進行中，Finder 裡的快速查看都會繼續顯示你的 Markdown 檔案。試用結束、尚未解鎖時，在 MarsDawn 裡開啟的文件內容會被遮住。"),
    ],
    pay_faq=[
        ("MarsDawn 要多少錢？", "MarsDawn 可從 Mac App Store 免費下載，14 天內可使用所有功能，之後一次 USD 4.99 的 App 內購買即可解鎖。"),
        ("有訂閱嗎？", "沒有。解鎖只買一次，不會續訂，之後也不會再扣款。開始試用同樣不用花錢。"),
        ("14 天試用結束後會怎樣？", "在你解鎖之前，無法在 MarsDawn 裡閱讀、編輯、輸出或列印文件：文件仍可開啟，但內容會被遮住。你的檔案維持你儲存時的樣子。"),
        ("試用結束後，快速查看還能用嗎？", "能。Finder 裡的快速查看不論有沒有試用都能用。免費的 marsdawn 命令列工具也會繼續把 Markdown 輸出成 PDF。"),
        ("需要帳號嗎？", "不需要。MarsDawn 不會要求你建立帳號。"),
    ],
    ql_title="Mac 的 Markdown 快速查看：在 Finder 預覽 .md 檔案 · MarsDawn",
    ql_desc="MarsDawn 的快速查看讓你在 Finder 按空白鍵就看到排版後的 Markdown，Mermaid 圖表、KaTeX 數學式和程式碼上色都在。試用期結束後，快速查看照常可用。",
    ql_h1="在 Finder 用快速查看預覽 Markdown。",
    ql_lead="在 Finder 選取 Markdown 檔案，按空白鍵。裝了 MarsDawn 之後，快速查看顯示的是排版後的頁面，不是純文字。",
    ql_shows_h="預覽會顯示什麼",
    ql_shows=[
        "排版後的頁面，和 MarsDawn 預覽窗格用的是同一個轉譯器。",
        "Mermaid 圖表、KaTeX 數學式和上色的程式碼區塊。",
        "你在 MarsDawn 選的預覽主題，淺色或深色。",
        "網路圖片依然會被擋下，放在檔案旁邊的圖片也可能只顯示佔位圖示。",
    ],
    ql_how_h="怎麼使用",
    ql_how_name="如何用快速查看預覽 Markdown 檔案",
    ql_steps=[
        ("安裝 MarsDawn。", "從 Mac App Store 下載 MarsDawn。快速查看擴充功能是 app 的一部分。"),
        ("選取 Markdown 檔案。", "在 Finder 點一下 .md 檔案。"),
        ("按空白鍵。", "排版後的預覽會打開，再按一次空白鍵就會關閉。"),
        ("看到純文字的話，把擴充功能打開。", "打開「系統設定」，前往「一般」▸「登入項目與延伸功能」，按一下「延伸功能」下「快速查看」旁的資訊按鈕，打開「MarsDawn Preview」，再按一下「完成」。"),
    ],
    ql_trial_h="不受試用期限制",
    ql_trial_p="試用期結束後，快速查看照常可用。試用中、試用結束後、解鎖之後，它顯示的都是同一份排版預覽。試用結束、尚未解鎖時，只有 MarsDawn 自己的視窗會遮住內容；Finder 裡的預覽不變。{pay_link}把三個階段並排列了出來。",
    ql_pay_link_text="試用與解鎖頁面",
    ql_next_h="接下來",
    ql_faq=[
        ("怎麼在 Finder 預覽 Markdown 檔案？", "選取檔案後按空白鍵。裝了 MarsDawn，快速查看會顯示排版後的頁面，包含 Mermaid 圖表、KaTeX 數學式和程式碼上色。"),
        ("14 天試用結束後，快速查看還能用嗎？", "能。快速查看不受試用期限制，試用中、試用結束後與解鎖之後都會繼續轉譯 Markdown 檔案。"),
        ("為什麼快速查看只顯示純文字？", "可能是快速查看擴充功能沒有打開。打開「系統設定」，前往「一般」▸「登入項目與延伸功能」，按一下「延伸功能」下「快速查看」旁的資訊按鈕，打開「MarsDawn Preview」，再按一下「完成」。"),
        ("快速查看要另外付費嗎？", "不用。快速查看擴充功能是 MarsDawn 的一部分，沒有另外的購買。MarsDawn 免費下載，14 天試用，之後一次 USD 4.99 解鎖；快速查看不論有沒有試用都能用。"),
        ("需要哪個版本的 macOS？", "MarsDawn 需要 macOS 26 或更新版本。"),
    ],
)

COPY["zh-hans"] = dict(
    desc="MarsDawn 是 Mac 原生 Markdown 编辑器：实时分栏预览、Mermaid、KaTeX、快速查看、PDF 导出。免费试用，之后一次 USD 4.99 解锁。",
    defn="MarsDawn 是 macOS 原生的 Markdown 编辑器，有实时分栏预览、Mermaid 图表、KaTeX 数学公式、快速查看与 PDF 导出，可免费试用 14 天，之后只要一次 USD 4.99 解锁。",
    ql_link="快速查看怎么用",
    faq_h="常见问题",
    ui="Markdown 快速查看",
    home_faq=[
        ("MarsDawn 是什么？", "MarsDawn 是 Mac 上原生的 Markdown 编辑器。源码旁边有实时预览，能画出 Mermaid 图表和 KaTeX 数学公式，在访达用快速查看预览 Markdown 文件，也能导出 PDF。"),
        ("MarsDawn 要订阅吗？", "不用。MarsDawn 免费下载，14 天内所有功能都能试用；之后一次 USD 4.99 的 App 内购买就能永久解锁。没有任何续订，也不需要账户。"),
        ("MarsDawn 有 iPhone 或 iPad 版吗？", "没有。MarsDawn 是 Mac app，需要 macOS 26 或更新版本，没有 iPhone 或 iPad 版。"),
        ("Claude Code 可以用 MarsDawn 打开文件吗？", "可以。免费的 marsdawn 命令行工具有 open 命令，能用 MarsDawn 打开 Markdown 文件，所以 Claude Code，或任何能执行 shell 命令的 agent，都能调用它。另有一个需要自行启用的 Claude Code hook，可以在 Claude 写入或编辑 Markdown 文件时自动打开。"),
        ("试用结束后，快速查看还能用吗？", "能。不论试用是否进行中，访达里的快速查看都会继续显示你的 Markdown 文件。试用结束、尚未解锁时，在 MarsDawn 里打开的文档内容会被遮住。"),
    ],
    pay_faq=[
        ("MarsDawn 要多少钱？", "MarsDawn 可从 Mac App Store 免费下载，14 天内可使用所有功能，之后一次 USD 4.99 的 App 内购买即可解锁。"),
        ("有订阅吗？", "没有。解锁只买一次，不会续订，之后也不会再扣款。开始试用同样不用花钱。"),
        ("14 天试用结束后会怎样？", "在你解锁之前，无法在 MarsDawn 里阅读、编辑、导出或打印文档：文档仍可打开，但内容会被遮住。你的文件保持你保存时的样子。"),
        ("试用结束后，快速查看还能用吗？", "能。访达里的快速查看不论有没有试用都能用。免费的 marsdawn 命令行工具也会继续把 Markdown 导出成 PDF。"),
        ("需要账户吗？", "不需要。MarsDawn 不会要求你创建账户。"),
    ],
    ql_title="Mac 的 Markdown 快速查看：在访达预览 .md 文件 · MarsDawn",
    ql_desc="MarsDawn 的快速查看让你在访达按空格键就能看到排版后的 Markdown，Mermaid 图表、KaTeX 数学公式和代码高亮都在。试用期结束后，快速查看照常可用。",
    ql_h1="在访达用快速查看预览 Markdown。",
    ql_lead="在访达选取 Markdown 文件，按空格键。装了 MarsDawn 之后，快速查看显示的是排版后的页面，不是纯文本。",
    ql_shows_h="预览会显示什么",
    ql_shows=[
        "排版后的页面，和 MarsDawn 预览窗格用的是同一个渲染器。",
        "Mermaid 图表、KaTeX 数学公式和高亮的代码块。",
        "你在 MarsDawn 里选的预览主题，浅色或深色。",
        "网络图片依然会被拦下，放在文件旁边的图片也可能只显示占位图标。",
    ],
    ql_how_h="怎么使用",
    ql_how_name="如何用快速查看预览 Markdown 文件",
    ql_steps=[
        ("安装 MarsDawn。", "从 Mac App Store 下载 MarsDawn。快速查看扩展是 app 的一部分。"),
        ("选取 Markdown 文件。", "在访达点一下 .md 文件。"),
        ("按空格键。", "排版后的预览会打开，再按一次空格键就会关闭。"),
        ("看到纯文本的话，把扩展打开。", "打开“系统设置”，前往“通用”▸“登录项与扩展”，点按“扩展”下“快速查看”旁边的信息按钮，打开“MarsDawn Preview”，然后点按“完成”。"),
    ],
    ql_trial_h="不受试用期限制",
    ql_trial_p="试用期结束后，快速查看照常可用。试用中、试用结束后、解锁之后，它显示的都是同一份排版预览。试用结束、尚未解锁时，只有 MarsDawn 自己的窗口会遮住内容；访达里的预览不变。{pay_link}把三个阶段并排列了出来。",
    ql_pay_link_text="试用与解锁页面",
    ql_next_h="接下来",
    ql_faq=[
        ("怎么在访达预览 Markdown 文件？", "选取文件后按空格键。装了 MarsDawn，快速查看会显示排版后的页面，包含 Mermaid 图表、KaTeX 数学公式和代码高亮。"),
        ("14 天试用结束后，快速查看还能用吗？", "能。快速查看不受试用期限制，试用中、试用结束后与解锁之后都会继续渲染 Markdown 文件。"),
        ("为什么快速查看只显示纯文本？", "可能是快速查看扩展没有打开。打开“系统设置”，前往“通用”▸“登录项与扩展”，点按“扩展”下“快速查看”旁边的信息按钮，打开“MarsDawn Preview”，然后点按“完成”。"),
        ("快速查看要另外付费吗？", "不用。快速查看扩展是 MarsDawn 的一部分，没有另外的购买。MarsDawn 免费下载，14 天试用，之后一次 USD 4.99 解锁；快速查看不论有没有试用都能用。"),
        ("需要哪个版本的 macOS？", "MarsDawn 需要 macOS 26 或更新版本。"),
    ],
)

COPY["ja"] = dict(
    desc="MarsDawn は Mac 向けのネイティブ Markdown エディタです。ライブ分割プレビュー、Mermaid、KaTeX、クイックルック、PDF 書き出し。無料で試せて、USD 4.99 の買い切り。",
    defn="MarsDawn は、ライブ分割プレビュー、Mermaid 図、KaTeX 数式、クイックルック、PDF 書き出しを備えたネイティブな macOS 向け Markdown エディタで、14日間無料で試せ、ロック解除は USD 4.99 の一度きりです。",
    ql_link="クイックルックの使い方",
    faq_h="よくある質問",
    ui="Markdown のクイックルック",
    home_faq=[
        ("MarsDawn とは何ですか？", "MarsDawn は Mac 向けのネイティブな Markdown エディタです。ソースの横にライブプレビューを表示し、Mermaid 図と KaTeX 数式を描画し、Finder のクイックルックで Markdown ファイルをプレビューでき、PDF にも書き出せます。"),
        ("MarsDawn はサブスクリプションですか？", "いいえ。MarsDawn は無料でダウンロードでき、14日間はすべての機能を試せます。そのあとは USD 4.99 のApp 内課金を一度行うだけで、ずっとロック解除されます。更新はなく、アカウントも不要です。"),
        ("MarsDawn は iPhone や iPad で使えますか？", "いいえ。MarsDawn は Mac アプリで、macOS 26 以降が必要です。iPhone 版や iPad 版はありません。"),
        ("Claude Code から MarsDawn でファイルを開けますか？", "はい。無料の marsdawn コマンドラインツールには open コマンドがあり、Markdown ファイルを MarsDawn で開けるので、Claude Code やシェルコマンドを実行できるエージェントから呼び出せます。Claude が Markdown ファイルを書いたり編集したりするたびに開く、任意で有効にする Claude Code フックもあります。"),
        ("トライアル期間が終わっても、クイックルックは使えますか？", "はい。トライアル期間中かどうかにかかわらず、Finder のクイックルックは Markdown ファイルを表示し続けます。トライアル期間が終わってロックを解除するまでは、MarsDawn で開いた書類の内容は覆われます。"),
    ],
    pay_faq=[
        ("MarsDawn の料金はいくらですか？", "MarsDawn は Mac App Store から無料でダウンロードできます。14日間はすべての機能を使え、そのあとは USD 4.99 の一度きりのApp 内課金でロックを解除できます。"),
        ("サブスクリプションはありますか？", "いいえ。ロック解除は一度きりの購入なので、更新も、あとからの請求もありません。トライアルを始めるのにも費用はかかりません。"),
        ("14日間のトライアルが終わるとどうなりますか？", "ロックを解除するまでは、MarsDawn で書類を読む、編集する、書き出す、プリントすることはできません。書類は開きますが、内容は覆われます。ファイルは保存したときのままです。"),
        ("トライアル期間が終わっても、クイックルックは使えますか？", "はい。Finder のクイックルックはトライアルの有無にかかわらず使えます。無料の marsdawn コマンドラインツールも、Markdown を PDF に書き出し続けます。"),
        ("アカウントは必要ですか？", "いいえ。MarsDawn がアカウントの作成を求めることはありません。"),
    ],
    ql_title="Mac の Markdown クイックルック：Finder で .md ファイルをプレビュー · MarsDawn",
    ql_desc="MarsDawn のクイックルックなら、Finder でスペースキーを押すだけで Markdown を描画して表示します。Mermaid 図、KaTeX 数式、ハイライトされたコードにも対応。トライアル終了後も使えます。",
    ql_h1="Finder のクイックルックで Markdown をプレビュー。",
    ql_lead="Finder で Markdown ファイルを選んでスペースキーを押します。MarsDawn をインストールしていれば、クイックルックはプレーンテキストではなく、描画されたページを表示します。",
    ql_shows_h="プレビューに表示されるもの",
    ql_shows=[
        "MarsDawn のプレビューペインと同じレンダラーで描画されたページ。",
        "Mermaid 図、KaTeX 数式、ハイライトされたコードブロック。",
        "MarsDawn で選んだプレビューテーマ（ライトまたはダーク）。",
        "Web の画像はブロックされたままで、ファイルの隣にある画像はプレースホルダとして表示されることがあります。",
    ],
    ql_how_h="使い方",
    ql_how_name="クイックルックで Markdown ファイルをプレビューする方法",
    ql_steps=[
        ("MarsDawn をインストールします。", "Mac App Store から MarsDawn をダウンロードします。クイックルックの機能拡張はアプリの一部です。"),
        ("Markdown ファイルを選びます。", "Finder で .md ファイルを一度クリックします。"),
        ("スペースキーを押します。", "描画されたプレビューが開きます。もう一度スペースキーを押すと閉じます。"),
        ("プレーンテキストが表示されたら、機能拡張をオンにします。", "「システム設定」を開き、「一般」▸「ログイン項目と機能拡張」に進んで、「機能拡張」の「クイックルック」の横にある情報ボタンをクリックし、「MarsDawn Preview」をオンにして「完了」をクリックします。"),
    ],
    ql_trial_h="トライアル期間の制限を受けません",
    ql_trial_p="トライアル終了後も、クイックルックはそのまま使えます。トライアル期間中も、終了後も、ロック解除後も、同じ描画済みのプレビューを表示します。トライアル期間が終わってロックを解除するまでは、MarsDawn 自身のウインドウだけが内容を覆い、Finder のプレビューは変わりません。{pay_link}では、3つの段階を並べて確認できます。",
    ql_pay_link_text="トライアルとロック解除のページ",
    ql_next_h="次に読む",
    ql_faq=[
        ("Finder で Markdown ファイルをプレビューするには？", "ファイルを選んでスペースキーを押します。MarsDawn をインストールしていれば、クイックルックは Mermaid 図、KaTeX 数式、ハイライトされたコードを含む、描画されたページを表示します。"),
        ("14日間のトライアルが終わっても、クイックルックは使えますか？", "はい。クイックルックはトライアル期間の制限を受けません。トライアル期間中も、終了後も、ロック解除後も、Markdown ファイルを描画し続けます。"),
        ("クイックルックがプレーンテキストを表示するのはなぜですか？", "クイックルックの機能拡張がオフになっている可能性があります。「システム設定」を開き、「一般」▸「ログイン項目と機能拡張」に進んで、「機能拡張」の「クイックルック」の横にある情報ボタンをクリックし、「MarsDawn Preview」をオンにして「完了」をクリックしてください。"),
        ("クイックルックは別料金ですか？", "いいえ。クイックルックの機能拡張は MarsDawn の一部で、別の購入は不要です。MarsDawn は無料でダウンロードでき、14日間試せて、ロック解除は USD 4.99 の一度きりです。クイックルックはトライアルの有無にかかわらず使えます。"),
        ("必要な macOS のバージョンは？", "MarsDawn には macOS 26 以降が必要です。"),
    ],
)

COPY["de"] = dict(
    desc="MarsDawn ist ein nativer Markdown-Editor für Mac: Live-Vorschau neben dem Quelltext, Mermaid, KaTeX, Übersicht, PDF-Export. Gratis testen, einmalig 4,99 USD.",
    defn="MarsDawn ist ein nativer Markdown-Editor für macOS mit Live-Vorschau neben dem Quelltext, Mermaid-Diagrammen, KaTeX-Formeln, Übersicht (Quick Look) und PDF-Export, 14 Tage gratis testbar und danach einmalig für 4,99 USD freischaltbar.",
    ql_link="So funktioniert die Übersicht",
    faq_h="Fragen und Antworten",
    ui="Quick Look für Markdown",
    home_faq=[
        ("Was ist MarsDawn?", "MarsDawn ist ein nativer Markdown-Editor für den Mac. Er zeigt neben dem Quelltext eine Live-Vorschau, zeichnet Mermaid-Diagramme und KaTeX-Formeln, zeigt Markdown-Dateien im Finder mit der Übersicht (Quick Look) an und exportiert PDF."),
        ("Ist MarsDawn ein Abo?", "Nein. MarsDawn ist ein kostenloser Download mit 14 Tagen Test aller Funktionen. Danach schaltet ein einmaliger In-App-Kauf für 4,99 USD die App dauerhaft frei. Nichts verlängert sich, und es gibt kein Konto."),
        ("Läuft MarsDawn auf dem iPhone oder iPad?", "Nein. MarsDawn ist eine Mac-App und braucht macOS 26 oder neuer. Es gibt keine App für iPhone oder iPad."),
        ("Kann Claude Code Dateien in MarsDawn öffnen?", "Ja. Das kostenlose Befehlszeilenprogramm marsdawn hat einen Befehl open, der eine Markdown-Datei in MarsDawn öffnet. Claude Code oder jeder Agent, der einen Shell-Befehl ausführen kann, kann ihn aufrufen. Ein optionaler Claude-Code-Hook kann jede Markdown-Datei öffnen, die Claude schreibt oder bearbeitet."),
        ("Funktioniert die Übersicht nach dem Ende des Tests noch?", "Ja. Die Übersicht (Quick Look) im Finder zeigt deine Markdown-Dateien weiterhin an, egal ob der Test läuft. Nach dem Ende des Tests öffnen sich Dokumente in MarsDawn mit verdecktem Inhalt, bis du freischaltest."),
    ],
    pay_faq=[
        ("Was kostet MarsDawn?", "MarsDawn ist ein kostenloser Download aus dem Mac App Store. 14 Tage lang kannst du alle Funktionen nutzen, danach schaltet ein einmaliger In-App-Kauf für 4,99 USD die App frei."),
        ("Gibt es ein Abo?", "Nein. Die Freischaltung ist ein einzelner Kauf, nichts verlängert sich, und später wird nichts abgebucht. Auch der Start des Tests kostet nichts."),
        ("Was passiert, wenn der 14-tägige Test endet?", "Bis du MarsDawn freischaltest, kannst du darin keine Dokumente mehr lesen, bearbeiten, exportieren oder drucken: Sie öffnen sich mit verdecktem Inhalt. Deine Dateien bleiben genau so, wie du sie gesichert hast."),
        ("Funktioniert die Übersicht nach dem Test noch?", "Ja. Die Übersicht (Quick Look) im Finder funktioniert mit und ohne Test. Auch das kostenlose Befehlszeilenprogramm marsdawn exportiert Markdown weiterhin als PDF."),
        ("Brauche ich ein Konto?", "Nein. MarsDawn verlangt nie, dass du ein Konto erstellst."),
    ],
    ql_title="Markdown-Vorschau im Finder: Quick Look für .md-Dateien auf dem Mac · MarsDawn",
    ql_desc="Mit MarsDawn zeigt die Übersicht Markdown im Finder per Leertaste gerendert: Mermaid, KaTeX, hervorgehobener Code. Sie funktioniert auch nach dem Test weiter.",
    ql_h1="Markdown im Finder mit der Übersicht ansehen.",
    ql_lead="Wähle im Finder eine Markdown-Datei aus und drücke die Leertaste. Mit installiertem MarsDawn zeigt die Übersicht (Quick Look) die gerenderte Seite statt Klartext.",
    ql_shows_h="Was die Vorschau zeigt",
    ql_shows=[
        "Die gerenderte Seite, gezeichnet vom selben Renderer wie der Vorschaubereich von MarsDawn.",
        "Mermaid-Diagramme, KaTeX-Formeln und hervorgehobene Codeblöcke.",
        "Das Vorschau-Thema, das du in MarsDawn gewählt hast, hell oder dunkel.",
        "Bilder aus dem Web bleiben blockiert, und Bilder neben der Datei können als Platzhalter erscheinen.",
    ],
    ql_how_h="So geht es",
    ql_how_name="So siehst du eine Markdown-Datei mit der Übersicht an",
    ql_steps=[
        ("Installiere MarsDawn.", "Lade MarsDawn aus dem Mac App Store. Die Erweiterung für die Übersicht gehört zur App."),
        ("Wähle eine Markdown-Datei aus.", "Klicke im Finder einmal auf eine .md-Datei."),
        ("Drücke die Leertaste.", "Die gerenderte Vorschau öffnet sich. Mit der Leertaste schließt du sie wieder."),
        ("Wenn du Klartext siehst, schalte die Erweiterung ein.", "Öffne die Systemeinstellungen, gehe zu Allgemein ▸ Anmeldeobjekte & Erweiterungen, klicke unter Erweiterungen neben „Übersicht“ auf die Taste „Info“, aktiviere „MarsDawn Preview“ und klicke auf „Fertig“."),
    ],
    ql_trial_h="Vom Test nicht gesperrt",
    ql_trial_p="Die Übersicht funktioniert auch nach dem Ende des Tests weiter. Sie zeigt dieselbe gerenderte Vorschau, solange der Test läuft, nach seinem Ende und nach der Freischaltung. Nach dem Ende des Tests und bis zur Freischaltung öffnen nur die eigenen Fenster von MarsDawn mit verdecktem Inhalt; die Vorschau im Finder bleibt unverändert. Die {pay_link} stellt alle drei Phasen nebeneinander.",
    ql_pay_link_text="Seite zu Test und Freischaltung",
    ql_next_h="Weiter",
    ql_faq=[
        ("Wie sehe ich eine Markdown-Datei im Finder in der Vorschau an?", "Wähle die Datei aus und drücke die Leertaste. Mit installiertem MarsDawn zeigt die Übersicht die gerenderte Seite mit Mermaid-Diagrammen, KaTeX-Formeln und hervorgehobenem Code."),
        ("Funktioniert die Übersicht nach dem 14-tägigen Test noch?", "Ja. Die Übersicht ist durch den Test nicht gesperrt. Sie rendert Markdown-Dateien weiterhin, während der Test läuft, nach seinem Ende und nach der Freischaltung."),
        ("Warum zeigt die Übersicht nur Klartext?", "Möglicherweise ist die Erweiterung für die Übersicht ausgeschaltet. Öffne die Systemeinstellungen, gehe zu Allgemein ▸ Anmeldeobjekte & Erweiterungen, klicke unter Erweiterungen neben „Übersicht“ auf die Taste „Info“, aktiviere „MarsDawn Preview“ und klicke auf „Fertig“."),
        ("Kostet die Übersicht extra?", "Nein. Die Erweiterung für die Übersicht gehört zu MarsDawn, ein separater Kauf ist nicht nötig. MarsDawn ist ein kostenloser Download mit 14 Tagen Test und einer einmaligen Freischaltung für 4,99 USD, und die Übersicht funktioniert mit und ohne Test."),
        ("Welche macOS-Version wird benötigt?", "MarsDawn braucht macOS 26 oder neuer."),
    ],
)

COPY["fr"] = dict(
    desc="MarsDawn est un éditeur Markdown natif pour Mac : aperçu en direct côte à côte, Mermaid, KaTeX, Coup d’œil, export PDF. Essai gratuit, puis 4,99 USD une fois.",
    defn="MarsDawn est un éditeur Markdown natif pour macOS avec aperçu en direct à côté de la source, diagrammes Mermaid, formules KaTeX, Coup d’œil (Quick Look) et export PDF, à essayer gratuitement 14 jours puis à déverrouiller une fois pour 4,99 USD.",
    ql_link="Comment fonctionne Coup d’œil",
    faq_h="Questions et réponses",
    ui="Quick Look pour Markdown",
    home_faq=[
        ("Qu’est-ce que MarsDawn ?", "MarsDawn est un éditeur Markdown natif pour Mac. Il affiche un aperçu en direct à côté de la source, dessine les diagrammes Mermaid et les formules KaTeX, affiche les fichiers Markdown dans le Finder avec Coup d’œil (Quick Look) et exporte en PDF."),
        ("MarsDawn est-il un abonnement ?", "Non. MarsDawn se télécharge gratuitement, avec 14 jours d’essai de toutes les fonctions. Ensuite, un seul achat intégré de 4,99 USD le déverrouille pour de bon. Rien ne se renouvelle, et il n’y a pas de compte."),
        ("MarsDawn fonctionne-t-il sur iPhone ou iPad ?", "Non. MarsDawn est une app Mac et demande macOS 26 ou une version ultérieure. Il n’existe pas d’app pour iPhone ou iPad."),
        ("Claude Code peut-il ouvrir des fichiers dans MarsDawn ?", "Oui. L’outil en ligne de commande gratuit marsdawn a une commande open qui ouvre un fichier Markdown dans MarsDawn, donc Claude Code, ou tout agent capable d’exécuter une commande shell, peut l’appeler. Un hook Claude Code facultatif peut ouvrir chaque fichier Markdown que Claude écrit ou modifie."),
        ("Coup d’œil fonctionne-t-il encore après la fin de l’essai ?", "Oui. Coup d’œil (Quick Look) dans le Finder continue d’afficher vos fichiers Markdown, que l’essai soit en cours ou non. Une fois l’essai terminé et tant que vous n’avez pas déverrouillé, les documents s’ouvrent dans MarsDawn avec leur contenu masqué."),
    ],
    pay_faq=[
        ("Combien coûte MarsDawn ?", "MarsDawn se télécharge gratuitement depuis le Mac App Store. Vous pouvez utiliser toutes les fonctions pendant 14 jours, puis un achat intégré unique de 4,99 USD le déverrouille."),
        ("Y a-t-il un abonnement ?", "Non. Le déverrouillage est un achat unique : rien ne se renouvelle et rien ne vous est facturé plus tard. Lancer l’essai ne coûte rien non plus."),
        ("Que se passe-t-il à la fin de l’essai de 14 jours ?", "Tant que vous n’avez pas déverrouillé MarsDawn, vous ne pouvez plus y lire, modifier, exporter ni imprimer de documents : ils s’ouvrent avec leur contenu masqué. Vos fichiers restent exactement comme vous les avez enregistrés."),
        ("Coup d’œil fonctionne-t-il encore après l’essai ?", "Oui. Coup d’œil (Quick Look) dans le Finder fonctionne avec ou sans l’essai. L’outil en ligne de commande gratuit marsdawn continue aussi d’exporter le Markdown en PDF."),
        ("Ai-je besoin d’un compte ?", "Non. MarsDawn ne vous demande jamais de créer un compte."),
    ],
    ql_title="Aperçu Markdown dans le Finder : Quick Look pour les fichiers .md sur Mac · MarsDawn",
    ql_desc="Avec MarsDawn, Coup d’œil affiche le Markdown mis en forme dans le Finder avec Espace : Mermaid, KaTeX, code coloré. Il fonctionne toujours après l’essai.",
    ql_h1="Prévisualiser le Markdown dans le Finder avec Coup d’œil.",
    ql_lead="Sélectionnez un fichier Markdown dans le Finder et appuyez sur Espace. Avec MarsDawn installé, Coup d’œil (Quick Look) affiche la page mise en forme au lieu du texte brut.",
    ql_shows_h="Ce que l’aperçu affiche",
    ql_shows=[
        "La page mise en forme, dessinée par le même moteur que le volet d’aperçu de MarsDawn.",
        "Des diagrammes Mermaid, des formules KaTeX et des blocs de code colorés.",
        "Le thème d’aperçu que vous avez choisi dans MarsDawn, en clair ou en sombre.",
        "Les images du web restent bloquées, et les images placées à côté du fichier peuvent apparaître sous forme d’espaces réservés.",
    ],
    ql_how_h="Comment l’utiliser",
    ql_how_name="Comment prévisualiser un fichier Markdown avec Coup d’œil",
    ql_steps=[
        ("Installez MarsDawn.", "Téléchargez MarsDawn depuis le Mac App Store. L’extension Coup d’œil fait partie de l’app."),
        ("Sélectionnez un fichier Markdown.", "Dans le Finder, cliquez une fois sur un fichier .md."),
        ("Appuyez sur Espace.", "L’aperçu mis en forme s’ouvre. Appuyez de nouveau sur Espace pour le fermer."),
        ("Si vous voyez du texte brut, activez l’extension.", "Ouvrez Réglages Système, allez dans Général ▸ Ouverture et extensions, cliquez sur le bouton d’informations en regard de « Coup d’œil » sous Extensions, activez « MarsDawn Preview », puis cliquez sur OK."),
    ],
    ql_trial_h="Non verrouillé par l’essai",
    ql_trial_p="Coup d’œil continue de fonctionner après la fin de l’essai. Il affiche le même aperçu mis en forme pendant l’essai, après sa fin et après le déverrouillage. Une fois l’essai terminé et tant que vous n’avez pas déverrouillé, seules les fenêtres de MarsDawn s’ouvrent avec leur contenu masqué ; les aperçus du Finder ne changent pas. La {pay_link} présente les trois phases côte à côte.",
    ql_pay_link_text="page sur l’essai et le déverrouillage",
    ql_next_h="Pour aller plus loin",
    ql_faq=[
        ("Comment prévisualiser un fichier Markdown dans le Finder ?", "Sélectionnez le fichier et appuyez sur Espace. Avec MarsDawn installé, Coup d’œil affiche la page mise en forme, avec diagrammes Mermaid, formules KaTeX et code coloré."),
        ("Coup d’œil fonctionne-t-il encore après l’essai de 14 jours ?", "Oui. Coup d’œil n’est pas verrouillé par l’essai. Il continue d’afficher les fichiers Markdown pendant l’essai, après sa fin et une fois l’app déverrouillée."),
        ("Pourquoi Coup d’œil affiche-t-il du texte brut ?", "L’extension Coup d’œil est peut-être désactivée. Ouvrez Réglages Système, allez dans Général ▸ Ouverture et extensions, cliquez sur le bouton d’informations en regard de « Coup d’œil » sous Extensions, activez « MarsDawn Preview », puis cliquez sur OK."),
        ("Coup d’œil est-il payant en plus ?", "Non. L’extension Coup d’œil fait partie de MarsDawn, sans achat séparé. MarsDawn se télécharge gratuitement, avec 14 jours d’essai et un déverrouillage unique à 4,99 USD, et Coup d’œil fonctionne avec ou sans l’essai."),
        ("Quelle version de macOS faut-il ?", "MarsDawn demande macOS 26 ou une version ultérieure."),
    ],
)

COPY["es"] = dict(
    desc="MarsDawn es un editor Markdown nativo para Mac: vista previa en vivo, Mermaid, KaTeX, Vista rápida, exportación PDF. Pruébalo gratis; luego, 4,99 USD una vez.",
    defn="MarsDawn es un editor de Markdown nativo para macOS con vista previa en vivo junto al código, diagramas Mermaid, fórmulas KaTeX, Vista rápida (Quick Look) y exportación a PDF, gratis durante 14 días y después 4,99 USD una sola vez para desbloquearlo.",
    ql_link="Cómo funciona Vista rápida",
    faq_h="Preguntas y respuestas",
    ui="Quick Look para Markdown",
    home_faq=[
        ("¿Qué es MarsDawn?", "MarsDawn es un editor de Markdown nativo para Mac. Muestra una vista previa en vivo junto al código, dibuja diagramas Mermaid y fórmulas KaTeX, muestra los archivos Markdown en el Finder con Vista rápida (Quick Look) y exporta a PDF."),
        ("¿MarsDawn es una suscripción?", "No. MarsDawn se descarga gratis y incluye 14 días de prueba de todas las funciones. Después, una sola compra dentro de la app por 4,99 USD lo desbloquea para siempre. Nada se renueva y no hay cuenta."),
        ("¿MarsDawn funciona en iPhone o iPad?", "No. MarsDawn es una app para Mac y necesita macOS 26 o posterior. No existe una app para iPhone ni iPad."),
        ("¿Puede Claude Code abrir archivos en MarsDawn?", "Sí. La herramienta de línea de comandos gratuita marsdawn tiene un comando open que abre un archivo Markdown en MarsDawn, así que Claude Code, o cualquier agente que pueda ejecutar un comando de shell, puede llamarlo. Un hook opcional de Claude Code puede abrir cada archivo Markdown que Claude escribe o edita."),
        ("¿Vista rápida sigue funcionando cuando termina la prueba?", "Sí. Vista rápida (Quick Look) en el Finder sigue mostrando tus archivos Markdown, esté o no en marcha la prueba. Cuando la prueba termina y hasta que desbloquees, los documentos se abren en MarsDawn con el contenido cubierto."),
    ],
    pay_faq=[
        ("¿Cuánto cuesta MarsDawn?", "MarsDawn se descarga gratis desde el Mac App Store. Puedes usar todas las funciones durante 14 días y después una compra única dentro de la app por 4,99 USD lo desbloquea."),
        ("¿Hay suscripción?", "No. El desbloqueo es una sola compra: nada se renueva y no se te cobra más adelante. Empezar la prueba tampoco cuesta nada."),
        ("¿Qué pasa cuando termina la prueba de 14 días?", "Hasta que desbloquees MarsDawn, no puedes leer, editar, exportar ni imprimir documentos en la app: se abren con el contenido cubierto. Tus archivos quedan exactamente como los guardaste."),
        ("¿Vista rápida sigue funcionando después de la prueba?", "Sí. Vista rápida (Quick Look) en el Finder funciona con o sin la prueba. La herramienta de línea de comandos gratuita marsdawn también sigue exportando Markdown a PDF."),
        ("¿Necesito una cuenta?", "No. MarsDawn nunca te pide que crees una cuenta."),
    ],
    ql_title="Vista previa de Markdown en el Finder: Quick Look para archivos .md en Mac · MarsDawn",
    ql_desc="Con MarsDawn, Vista rápida renderiza Markdown en el Finder con la barra espaciadora: Mermaid, KaTeX y código resaltado. Sigue funcionando tras la prueba.",
    ql_h1="Previsualiza Markdown en el Finder con Vista rápida.",
    ql_lead="Selecciona un archivo Markdown en el Finder y presiona la barra espaciadora. Con MarsDawn instalado, Vista rápida (Quick Look) muestra la página renderizada en lugar de texto sin formato.",
    ql_shows_h="Qué muestra la vista previa",
    ql_shows=[
        "La página renderizada, dibujada por el mismo renderizador que el panel de vista previa de MarsDawn.",
        "Diagramas Mermaid, fórmulas KaTeX y bloques de código resaltados.",
        "El tema de vista previa que elegiste en MarsDawn, claro u oscuro.",
        "Las imágenes de la web siguen bloqueadas, y las imágenes guardadas junto al archivo pueden aparecer como marcadores de posición.",
    ],
    ql_how_h="Cómo usarla",
    ql_how_name="Cómo previsualizar un archivo Markdown con Vista rápida",
    ql_steps=[
        ("Instala MarsDawn.", "Descarga MarsDawn desde el Mac App Store. La extensión de Vista rápida forma parte de la app."),
        ("Selecciona un archivo Markdown.", "En el Finder, haz clic una vez en un archivo .md."),
        ("Presiona la barra espaciadora.", "Se abre la vista previa renderizada. Vuelve a presionar la barra espaciadora para cerrarla."),
        ("Si ves texto sin formato, activa la extensión.", "Abre Ajustes del Sistema, ve a General ▸ Ítems de inicio y extensiones, haz clic en el botón de información junto a «Vista rápida» en Extensiones, activa «MarsDawn Preview» y haz clic en Aceptar."),
    ],
    ql_trial_h="No queda bloqueada por la prueba",
    ql_trial_p="Vista rápida sigue funcionando cuando termina la prueba. Muestra la misma vista previa renderizada mientras la prueba está en marcha, después de que termine y tras desbloquear. Cuando la prueba termina y hasta que desbloquees, solo las ventanas de MarsDawn se abren con el contenido cubierto; las vistas previas del Finder no cambian. La {pay_link} presenta las tres fases una al lado de otra.",
    ql_pay_link_text="página sobre la prueba y el desbloqueo",
    ql_next_h="Siguiente",
    ql_faq=[
        ("¿Cómo previsualizo un archivo Markdown en el Finder?", "Selecciona el archivo y presiona la barra espaciadora. Con MarsDawn instalado, Vista rápida muestra la página renderizada, con diagramas Mermaid, fórmulas KaTeX y código resaltado."),
        ("¿Vista rápida sigue funcionando después de la prueba de 14 días?", "Sí. Vista rápida no queda bloqueada por la prueba. Sigue renderizando archivos Markdown mientras la prueba está en marcha, después de que termine y una vez desbloqueada la app."),
        ("¿Por qué Vista rápida muestra texto sin formato?", "Puede que la extensión de Vista rápida esté desactivada. Abre Ajustes del Sistema, ve a General ▸ Ítems de inicio y extensiones, haz clic en el botón de información junto a «Vista rápida» en Extensiones, activa «MarsDawn Preview» y haz clic en Aceptar."),
        ("¿Vista rápida cuesta algo aparte?", "No. La extensión de Vista rápida forma parte de MarsDawn, sin compra aparte. MarsDawn se descarga gratis, con 14 días de prueba y un desbloqueo único de 4,99 USD, y Vista rápida funciona con o sin la prueba."),
        ("¿Qué versión de macOS necesita?", "MarsDawn necesita macOS 26 o posterior."),
    ],
)

COPY["ko"] = dict(
    desc="MarsDawn은 Mac용 네이티브 Markdown 편집기입니다. 소스 옆 실시간 미리보기, Mermaid, KaTeX, 훑어보기, PDF 내보내기. 무료로 체험하고, 잠금 해제는 한 번만 USD 4.99.",
    defn="MarsDawn은 소스 옆 실시간 미리보기, Mermaid 다이어그램, KaTeX 수식, 훑어보기(Quick Look), PDF 내보내기를 갖춘 macOS 네이티브 Markdown 편집기로, 14일 동안 무료로 체험할 수 있고 잠금 해제는 한 번만 USD 4.99입니다.",
    ql_link="훑어보기 사용법",
    faq_h="자주 묻는 질문",
    ui="Markdown 훑어보기",
    home_faq=[
        ("MarsDawn은 무엇인가요?", "MarsDawn은 Mac용 네이티브 Markdown 편집기입니다. 소스 옆에 실시간 미리보기를 보여 주고, Mermaid 다이어그램과 KaTeX 수식을 그리며, Finder의 훑어보기(Quick Look)로 Markdown 파일을 미리 볼 수 있고, PDF로 내보낼 수 있습니다."),
        ("MarsDawn은 구독인가요?", "아니요. MarsDawn은 무료로 다운로드할 수 있고, 14일 동안 모든 기능을 체험할 수 있습니다. 그 뒤에는 USD 4.99의 앱 내 구입 한 번으로 영구히 잠금 해제됩니다. 갱신되는 것은 없고, 계정도 없습니다."),
        ("MarsDawn은 iPhone이나 iPad에서 쓸 수 있나요?", "아니요. MarsDawn은 Mac 앱이며 macOS 26 이상이 필요합니다. iPhone용이나 iPad용 앱은 없습니다."),
        ("Claude Code가 MarsDawn에서 파일을 열 수 있나요?", "네. 무료 marsdawn 명령줄 도구에는 Markdown 파일을 MarsDawn에서 여는 open 명령이 있어서, Claude Code나 셸 명령을 실행할 수 있는 모든 에이전트가 호출할 수 있습니다. 선택적으로 켜는 Claude Code 훅은 Claude가 쓰거나 편집한 Markdown 파일을 열어 줍니다."),
        ("체험이 끝나도 훑어보기를 쓸 수 있나요?", "네. 체험 중이든 아니든 Finder의 훑어보기는 Markdown 파일을 계속 보여 줍니다. 체험이 끝나고 잠금을 해제하기 전까지는 MarsDawn에서 연 문서의 내용이 가려집니다."),
    ],
    pay_faq=[
        ("MarsDawn은 얼마인가요?", "MarsDawn은 Mac App Store에서 무료로 다운로드할 수 있습니다. 14일 동안 모든 기능을 쓸 수 있고, 그 뒤에는 USD 4.99의 일회성 앱 내 구입으로 잠금을 해제합니다."),
        ("구독이 있나요?", "아니요. 잠금 해제는 한 번의 구입이라 갱신되는 것이 없고, 나중에 결제되는 일도 없습니다. 체험을 시작하는 데도 비용이 들지 않습니다."),
        ("14일 체험이 끝나면 어떻게 되나요?", "MarsDawn의 잠금을 해제하기 전까지는 그 안에서 문서를 읽거나 편집하거나 내보내거나 프린트할 수 없습니다. 문서는 열리지만 내용이 가려집니다. 파일은 저장한 그대로 남아 있습니다."),
        ("체험이 끝나도 훑어보기를 쓸 수 있나요?", "네. Finder의 훑어보기는 체험 여부와 관계없이 작동합니다. 무료 marsdawn 명령줄 도구도 Markdown을 계속 PDF로 내보냅니다."),
        ("계정이 필요한가요?", "아니요. MarsDawn은 계정을 만들라고 요구하지 않습니다."),
    ],
    ql_title="Finder에서 Markdown 미리보기: Mac의 .md 파일 훑어보기(Quick Look) · MarsDawn",
    ql_desc="MarsDawn의 훑어보기로 Finder에서 스페이스 바를 누르면 Markdown이 렌더링되어 보입니다. Mermaid, KaTeX, 강조된 코드도 표시됩니다. 체험이 끝난 뒤에도 계속 작동합니다.",
    ql_h1="Finder의 훑어보기로 Markdown 미리보기.",
    ql_lead="Finder에서 Markdown 파일을 선택하고 스페이스 바를 누르세요. MarsDawn이 설치되어 있으면 훑어보기(Quick Look)가 일반 텍스트 대신 렌더링된 페이지를 보여 줍니다.",
    ql_shows_h="미리보기에 보이는 것",
    ql_shows=[
        "MarsDawn의 미리보기 패널과 같은 렌더러로 그린 렌더링된 페이지.",
        "Mermaid 다이어그램, KaTeX 수식, 강조된 코드 블록.",
        "MarsDawn에서 고른 미리보기 테마(라이트 또는 다크).",
        "웹 이미지는 계속 차단되며, 파일 옆에 있는 이미지는 자리 표시자로 나타날 수 있습니다.",
    ],
    ql_how_h="사용 방법",
    ql_how_name="훑어보기로 Markdown 파일을 미리 보는 방법",
    ql_steps=[
        ("MarsDawn을 설치하세요.", "Mac App Store에서 MarsDawn을 다운로드하세요. 훑어보기 확장 프로그램은 앱의 일부입니다."),
        ("Markdown 파일을 선택하세요.", "Finder에서 .md 파일을 한 번 클릭하세요."),
        ("스페이스 바를 누르세요.", "렌더링된 미리보기가 열립니다. 스페이스 바를 다시 누르면 닫힙니다."),
        ("일반 텍스트가 보이면 확장 프로그램을 켜세요.", "시스템 설정을 열고 일반 ▸ 로그인 항목 및 확장 프로그램으로 이동한 다음, 확장 프로그램 아래 ‘훑어보기’ 옆의 정보 버튼을 클릭하고 ‘MarsDawn Preview’를 켠 뒤 완료를 클릭하세요."),
    ],
    ql_trial_h="체험 기간의 제한을 받지 않습니다",
    ql_trial_p="훑어보기는 체험이 끝난 뒤에도 계속 작동합니다. 체험 중에도, 체험이 끝난 뒤에도, 잠금을 해제한 뒤에도 같은 렌더링된 미리보기를 보여 줍니다. 체험이 끝나고 잠금을 해제하기 전까지는 MarsDawn 자체의 윈도우만 내용이 가려지고, Finder의 미리보기는 그대로입니다. {pay_link}에서 세 단계를 나란히 볼 수 있습니다.",
    ql_pay_link_text="체험과 잠금 해제 페이지",
    ql_next_h="다음으로",
    ql_faq=[
        ("Finder에서 Markdown 파일을 미리 보려면 어떻게 하나요?", "파일을 선택하고 스페이스 바를 누르세요. MarsDawn이 설치되어 있으면 훑어보기가 Mermaid 다이어그램, KaTeX 수식, 강조된 코드를 포함한 렌더링된 페이지를 보여 줍니다."),
        ("14일 체험이 끝나도 훑어보기를 쓸 수 있나요?", "네. 훑어보기는 체험 기간의 제한을 받지 않습니다. 체험 중에도, 체험이 끝난 뒤에도, 잠금을 해제한 뒤에도 Markdown 파일을 계속 렌더링합니다."),
        ("훑어보기에 일반 텍스트만 보이는 이유는 무엇인가요?", "훑어보기 확장 프로그램이 꺼져 있을 수 있습니다. 시스템 설정을 열고 일반 ▸ 로그인 항목 및 확장 프로그램으로 이동한 다음, 확장 프로그램 아래 ‘훑어보기’ 옆의 정보 버튼을 클릭하고 ‘MarsDawn Preview’를 켠 뒤 완료를 클릭하세요."),
        ("훑어보기는 따로 비용이 드나요?", "아니요. 훑어보기 확장 프로그램은 MarsDawn의 일부이며 별도 구입이 필요 없습니다. MarsDawn은 무료로 다운로드할 수 있고, 14일 체험 뒤 잠금 해제는 한 번만 USD 4.99이며, 훑어보기는 체험 여부와 관계없이 작동합니다."),
        ("어떤 버전의 macOS가 필요한가요?", "MarsDawn에는 macOS 26 이상이 필요합니다."),
    ],
)
